name: pages

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]


concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Submodules
      run: |
        git submodule update --init --single-branch external/webrogue/
        cd external/webrogue/
        git submodule update --init --recursive --single-branch \
          external/libuv/ \
          external/uvwasi/ \
          external/xz/ \
          mods/brogue \
          mods/coremark

    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        ./emsdk/emsdk install latest
        ./emsdk/emsdk activate latest
    
    - name: Install packages
      run: |
        sudo apt-get install python3-zstd

    - name: Build mods
      run:
        cmake -B mods_build -S external/webrogue/mods \
          --toolchain=tools/generated_toolchain.cmake \
          -DCMAKE_MODULE_PATH=$(pwd)/external/webrogue/mods/cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DWEBROGUE_MOD_NAMES="core;coremark"

        cmake --build mods_build --target final_linking

        cmake -B mods_build -S external/webrogue/mods \
          --toolchain=tools/generated_toolchain.cmake \
          -DCMAKE_MODULE_PATH=$(pwd)/external/webrogue/mods/cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DWEBROGUE_MOD_NAMES="core;brogue"
          
        cmake --build mods_build --target final_linking

    - name: Build using Emscripten
      run: |
        . ./emsdk/emsdk_env.sh
        emcmake cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
        cmake --build build --target pack_artifacts -j

    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: Build using Jekyll 
      run: |        
        bundle install
        JEKYLL_ENV=production bundle exec jekyll build
        
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
