name: update_submodule

on:
  workflow_dispatch:

jobs:
  update_submodule:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v4
        
    - name: Submodules
      run: |
        git submodule update --init external/webrogue
        sh -c "cd external/webrogue; git pull origin main"
    
    - uses: EndBug/add-and-commit@v9

    - name: Trigger Build
      run: |
        gh workflow run pages
